# see http://www.appveyor.com/docs/appveyor-yml

##### ENABLE REMOVE RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################

#---------------------------------#
#      build configuration        #
#---------------------------------#
build_script:
 - cmd: msbuild .\src\.build\lessio.msbuild /p:TheVersion=0.0.0.0 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#       tests configuration       #
#---------------------------------#
environment:
  LESSIO_TEST_FILES: '%APPVEYOR_BUILD_FOLDER%\src\LessIO.Tests\TestFiles\'

test:
 assemblies:
  - .\src\.deploy\LessIO.Tests.dll

artifacts:
- path: '.deploy\nuget-package\*.nupkg'
- path: '.deploy\nuget-package\*.zip'
- path: '.deploy\LessIO.dll'

##### KEEP RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################