# see http://www.appveyor.com/docs/appveyor-yml

##### ENABLE REMOVE RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################

#---------------------------------#
#      build configuration        #
#---------------------------------#
build_script:
 - cmd: 'msbuild .\src\.build\lessio.msbuild /p:TheVersion="%APPVEYOR_BUILD_NUMBER%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

#---------------------------------#
#       tests configuration       #
#---------------------------------#
environment:
  LESSIO_TEST_FILES: '%APPVEYOR_BUILD_FOLDER%\src\LessIO.Tests\TestFiles\'

test:
 assemblies:
  - .\src\.deploy\LessIO.Tests.dll

artifacts:
- path: 'src\.deploy\nuget-package\*.nupkg'
- path: 'src\.deploy\*.zip'
- path: 'src\.deploy\LessIO.dll'

##### KEEP RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################