# see http://www.appveyor.com/docs/appveyor-yml
#---------------------------------#
#      build configuration        #
#---------------------------------#
build_script:
 - cmd: msbuild .\src\.build\lessio.msbuild /p:TheVersion=0.0.0.0 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#       tests configuration       #
#---------------------------------#
environment:
  LESSIO_TEST_FILES: '%APPVEYOR_BUILD_FOLDER%\src\LessIO.Tests\TestFiles\'

test:
 assemblies:
  - .\src\.deploy\LessIO.Tests.dll
